
networks:
  app:
    driver: bridge

volumes:
  pg_data:
  minio_data:

services:
  app: 
    build:
      context: .
      dockerfile: ./resources/docker/app.local.dockerfile
    environment:
      DEBUG: ${DEBUG}
      
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432

      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_HOST: s3
      S3_PORT: 9000
    volumes:
      - ./src:/app/src
      - ./resources/logs:/app/resources/logs
      - ./alembic:/app/alembic
    ports:
      - 8000:8000
    networks:
      - app
    restart: no
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
  db: 
    image: postgres:17.8-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    restart: no
    networks:
      - app
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 1
  s3:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    restart: no
    networks:
      - app
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 1
      